version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root       
      POSTGRES_PASSWORD: 'Skyrim2024'   
      POSTGRES_DB: netflix-clone   
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
